plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  
  - - '@semantic-release/exec'
    - prepareCmd: "find Assets/LogKit -name AssemblyInfo.cs -exec sed -i -e '/AssemblyVersion/s/\"[^\"]*\"/\"${nextRelease.version}\"/' {} + && sed -i -e 's|https://github.com/nicolas-stephan/NS-LogKit.git?path=/Assets/LogKit#v[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+|https://github.com/nicolas-stephan/NS-LogKit.git?path=/Assets/LogKit#v${nextRelease.version}|g' README.md docs/manual/installation.md"

  - - '@semantic-release/changelog'
    - changelogFile: 'Assets/LogKit/CHANGELOG.md'

  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: "Assets/LogKit"
      
  - - '@semantic-release/git'
    - assets:
        - 'Assets/LogKit/**/AssemblyInfo.cs'
        - 'Assets/LogKit/package.json'
        - 'Assets/LogKit/CHANGELOG.md'
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      
  - '@semantic-release/github'